# Generated by Django 3.0.6 on 2020-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_dolist_dday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolist',
            name='dday',
            field=models.IntegerField(default=0),
        ),
    ]
