# Generated by Django 3.0.6 on 2020-06-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200531_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolist',
            name='img',
            field=models.TextField(default=3131),
            preserve_default=False,
        ),
    ]
